name: Build Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  building:
    name: building
    runs-on: ubuntu-latest
    steps:
    - name: switch to target branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install dependencies then build
      run: yarn install && yarn build
